# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'happy.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(645, 789)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.topic_1 = QtWidgets.QLabel(Frame)
        self.topic_1.setScaledContents(True)
        self.topic_1.setAlignment(QtCore.Qt.AlignCenter)
        self.topic_1.setObjectName("topic_1")
        self.verticalLayout_5.addWidget(self.topic_1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Frame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 621, 236))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setStyleSheet("font: 15pt \"楷体\";")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(300)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(100)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_8.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.topic_2 = QtWidgets.QLabel(Frame)
        self.topic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.topic_2.setObjectName("topic_2")
        self.verticalLayout_6.addWidget(self.topic_2)
        self.forceAndBtnlLayout = QtWidgets.QHBoxLayout()
        self.forceAndBtnlLayout.setContentsMargins(-1, -1, 20, -1)
        self.forceAndBtnlLayout.setSpacing(20)
        self.forceAndBtnlLayout.setObjectName("forceAndBtnlLayout")
        self.forceLayout_3 = QtWidgets.QVBoxLayout()
        self.forceLayout_3.setObjectName("forceLayout_3")
        self.forceHlLayout_2 = QtWidgets.QHBoxLayout()
        self.forceHlLayout_2.setSpacing(0)
        self.forceHlLayout_2.setObjectName("forceHlLayout_2")
        self.forceLabel_2 = QtWidgets.QLabel(Frame)
        self.forceLabel_2.setStyleSheet("\n"
"font: 16pt \"隶书\";")
        self.forceLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.forceLabel_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.forceLabel_2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.forceLabel_2.setObjectName("forceLabel_2")
        self.forceHlLayout_2.addWidget(self.forceLabel_2)
        self.forcNumberlabel_2 = QtWidgets.QLabel(Frame)
        self.forcNumberlabel_2.setStyleSheet("font: 16pt \"Agency FB\";")
        self.forcNumberlabel_2.setObjectName("forcNumberlabel_2")
        self.forceHlLayout_2.addWidget(self.forcNumberlabel_2)
        self.forceHlLayout_2.setStretch(1, 1)
        self.forceLayout_3.addLayout(self.forceHlLayout_2)
        self.forceHlLayout = QtWidgets.QHBoxLayout()
        self.forceHlLayout.setSpacing(0)
        self.forceHlLayout.setObjectName("forceHlLayout")
        self.forceLabel = QtWidgets.QLabel(Frame)
        self.forceLabel.setStyleSheet("\n"
"font: 16pt \"隶书\";")
        self.forceLabel.setTextFormat(QtCore.Qt.AutoText)
        self.forceLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.forceLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.forceLabel.setObjectName("forceLabel")
        self.forceHlLayout.addWidget(self.forceLabel)
        self.forcNumberlabel = QtWidgets.QLabel(Frame)
        self.forcNumberlabel.setStyleSheet("font: 16pt \"Agency FB\";")
        self.forcNumberlabel.setObjectName("forcNumberlabel")
        self.forceHlLayout.addWidget(self.forcNumberlabel)
        self.forceHlLayout.setStretch(1, 1)
        self.forceLayout_3.addLayout(self.forceHlLayout)
        self.forceAndBtnlLayout.addLayout(self.forceLayout_3)
        self.breakthroughBtn = QtWidgets.QPushButton(Frame)
        self.breakthroughBtn.setStyleSheet("font: 16pt \"黑体\";\n"
"width:40%;\n"
"height:40%;")
        self.breakthroughBtn.setIconSize(QtCore.QSize(16, 16))
        self.breakthroughBtn.setAutoRepeat(False)
        self.breakthroughBtn.setAutoExclusive(True)
        self.breakthroughBtn.setAutoRepeatDelay(100)
        self.breakthroughBtn.setAutoDefault(False)
        self.breakthroughBtn.setDefault(False)
        self.breakthroughBtn.setFlat(False)
        self.breakthroughBtn.setObjectName("breakthroughBtn")
        self.forceAndBtnlLayout.addWidget(self.breakthroughBtn)
        self.verticalLayout_6.addLayout(self.forceAndBtnlLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.topic_3 = QtWidgets.QLabel(Frame)
        self.topic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.topic_3.setObjectName("topic_3")
        self.verticalLayout_7.addWidget(self.topic_3)
        self.guessAndBtnLayout = QtWidgets.QHBoxLayout()
        self.guessAndBtnLayout.setContentsMargins(0, 1, 20, 1)
        self.guessAndBtnLayout.setSpacing(20)
        self.guessAndBtnLayout.setObjectName("guessAndBtnLayout")
        self.guessHlLayout = QtWidgets.QHBoxLayout()
        self.guessHlLayout.setSpacing(0)
        self.guessHlLayout.setObjectName("guessHlLayout")
        self.guessLabel = QtWidgets.QLabel(Frame)
        self.guessLabel.setStyleSheet("\n"
"font: 16pt \"隶书\";")
        self.guessLabel.setTextFormat(QtCore.Qt.AutoText)
        self.guessLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.guessLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.guessLabel.setObjectName("guessLabel")
        self.guessHlLayout.addWidget(self.guessLabel)
        self.guessNumberlabel = QtWidgets.QLabel(Frame)
        self.guessNumberlabel.setStyleSheet("font: 16pt \"Agency FB\";")
        self.guessNumberlabel.setObjectName("guessNumberlabel")
        self.guessHlLayout.addWidget(self.guessNumberlabel)
        self.guessHlLayout.setStretch(1, 1)
        self.guessAndBtnLayout.addLayout(self.guessHlLayout)
        self.guessBtn = QtWidgets.QPushButton(Frame)
        self.guessBtn.setStyleSheet("font: 16pt \"华文行楷\";\n"
"width:40%;\n"
"height:40%;")
        self.guessBtn.setObjectName("guessBtn")
        self.guessAndBtnLayout.addWidget(self.guessBtn)
        self.guessAndBtnLayout.setStretch(0, 1)
        self.verticalLayout_7.addLayout(self.guessAndBtnLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stateLabel = QtWidgets.QLabel(Frame)
        self.stateLabel.setObjectName("stateLabel")
        self.verticalLayout_4.addWidget(self.stateLabel)
        self.label = QtWidgets.QLabel(Frame)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("pic/stop.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.startBtn = QtWidgets.QPushButton(Frame)
        self.startBtn.setStyleSheet("with:40%;\n"
"font: 16pt \"黑体\";\n"
"height:40%")
        self.startBtn.setObjectName("startBtn")
        self.verticalLayout_3.addWidget(self.startBtn)
        self.stopBtn = QtWidgets.QPushButton(Frame)
        self.stopBtn.setStyleSheet("with:40%;\n"
"height:40%;\n"
"font: 16pt \"黑体\";")
        self.stopBtn.setIconSize(QtCore.QSize(16, 32))
        self.stopBtn.setObjectName("stopBtn")
        self.verticalLayout_3.addWidget(self.stopBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.exitBtn = QtWidgets.QPushButton(Frame)
        self.exitBtn.setStyleSheet("font: 16pt \"华文新魏\";")
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout_8.addWidget(self.exitBtn)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.topic_1.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:16pt;\">风云榜</span></p></body></html>"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Frame", "1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Frame", "名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Frame", "原力值"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Frame", "asdfghjklzxcvb"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("Frame", "0"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.topic_2.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt;\">消耗1000000000000000000（10^18)个原力碎片获取一点原力值</span></p></body></html>"))
        self.forceLabel_2.setText(_translate("Frame", "<html><head/><body><p>原力碎片：</p></body></html>"))
        self.forcNumberlabel_2.setText(_translate("Frame", "0"))
        self.forceLabel.setText(_translate("Frame", "原力："))
        self.forcNumberlabel.setText(_translate("Frame", "0"))
        self.breakthroughBtn.setText(_translate("Frame", "突破"))
        self.topic_3.setText(_translate("Frame", "<html><head/><body><p><span style=\" font-size:14pt;\">消耗原力碎片，有概率获得原力值</span></p></body></html>"))
        self.guessLabel.setText(_translate("Frame", "<html><head/><body><p>氪金：</p></body></html>"))
        self.guessNumberlabel.setText(_translate("Frame", "0"))
        self.guessBtn.setText(_translate("Frame", "拼一把"))
        self.stateLabel.setText(_translate("Frame", "<html><head/><body><p align=\"center\">休息中<span style=\" font-size:14pt;\">。。。</span></p></body></html>"))
        self.startBtn.setText(_translate("Frame", "开始修炼"))
        self.stopBtn.setText(_translate("Frame", "结束修炼"))
        self.exitBtn.setText(_translate("Frame", "退出"))


